version: '3'
services:
  # message / task queue
  redis:
    image: redis
    ports:
      - "6379:6379"

  # task scheduler - enqueue tasks which result in celery picking them up
  celery-beat:
    build: ./app
    command: celery -A tasks beat --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      MESSAGE_QUEUE_URL: redis://redis:6379

  # task worker - picks up and fulfills tasks from the queue; writes reports to disk in /app/workspace/
  celery:
    build: ./app
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      MESSAGE_QUEUE_URL: redis://redis:6379

  # web interface - visualizes ML project reports stored on disk as JSON files in /app/workspace/
  evidently-ui:
    build: ./app
    # sleep 5 seconds, if evidently ui checks worskpace too early it doesn't register the project if just created
    command: sh -c "sleep 5 && evidently ui"
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'