version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: ./app
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis

  celery-beat:
    build: ./app
    command: celery -A tasks beat --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis

  evidently-ui:
    build: ./app
    command: evidently ui 
    volumes:
      - ./app:/app
    depends_on:
      - redis
    ports:
      - '8000:8000'